config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :grupo
  resources :equipos
  resources :resultados



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/equipo.rb
class Equipo < ApplicationRecord
validates :cod_equipo, numericality: true,
          uniqueness: {message:"%{value} no es único"}
validates :nom_equipo,presence: true,
           length: {minimum: 5}
end

app/models/grupo.rb
class Grupo < ApplicationRecord
  validates :cod_tipo_equipo,numericality: true,
            uniqueness: {message:"%{value} no es único"}
  validates :nom_tipo_equipo,presence: true,
            length: {minimum: 5}
  validates :descripcion,presence: true,
            length: {minimum: 10}

end

app/models/resultado.rb
class Resultado < ApplicationRecord
  validates :id, numericality: true,
            uniqueness: {message:"%{value} no es único"}
  validates :enfrentamiento, presence: true,
            length: {minimum: 5}
  validates :goles_marcados,presence: true
  validates :goles_recibidos,presence: true
  validates :puntos_partido,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/equipos_controller.rb
class EquiposController < ApplicationController
before_action :find_equipo, only: [:edit, :update, :show, :delete]

def index
 @equipo = Equipo.all
end

def new
  @equipo = Equipo.new
end

def create
  @equipo = Equipo.new(equipo_params)
  if @equipo.save
    flash[:notice] = "Creacion de equipo exitosa"
  redirect_to @equipo
  else
    flash[:alert] = "Error Creando equipo"
    render 'new'
  end
end

def show
  @equipo = Equipo.find(params[:id])
end

def edit
  @equipo = Equipo.find(params[:id])
end

def update
  if @equipo.update_attributes(post_params)
    flash[:notice] = "Actualizacion exitosa!"
    redirect_to equipo_path(@posts)
  else
    flash[:alert] = "Error no se pudo actualizar !"
    render :edit
  end
end


def delete
  if @equipo.delete
    flash[:notice] = "Borrado exitoso!"
    redirect_to equipos_path
  else
    flash[:alert] = "No se pudo borrar!"
  end
end
private
def equipo_params
params.require(:equipo).permit(:id,:cod_equipo,:nom_equipo, :activo_equipo, :fecha_creacion, :porcentaje)
end
def find_equipo
  @equipo = Equipo.find(params[:id])
end
end

app/controllers/grupo_controller.rb
class GrupoController < ApplicationController
  before_action :find_grupos, only: [:edit, :update, :show, :delete]

  def index
    @grupos = Grupo.all
  end

  def new
    @grupos = Grupo.new
  end

  def create
    @grupos = Grupo.new(grupos_params)
    if @grupos.save
      flash[:notice] = "Creacion de grupo exitosa"
      redirect_to @grupos
    else
      flash[:alert] = "Error Creando grupo"
      render 'new'
    end
  end

  def show
    @grupos = Grupo.find(params[:id])

  end

  def edit
    @grupos = Grupo.find(params[:id])
  end

  def update
    if @grupos.update_attributes(post_params)
      flash[:notice] = "Actualizacion exitosa!"
      redirect_to grupos_path(@posts)
    else
      flash[:alert] = "Error no se pudo actualizar !"
      render :edit
    end
  end


  def delete
    if @grupos.delete
      flash[:notice] = "Borrado exitoso!"
      redirect_to grupos_path
    else
      flash[:alert] = "No se pudo borrar!"
    end
  end
  private
  def grupos_params
    params.require(:grupo).permit(:id,:nom_tipo_equipo, :descripcion)
  end

  def find_grupos
    @grupos = Grupo.find(params[:id])
  end
end

app/controllers/resultados_controller.rb
class ResultadosController < ApplicationController
  before_action :find_resultado, only: [:edit, :update, :show, :delete]

  def index
    @resultado = Resultado.all
  end

  def new
    @resultado = Resultado.new
  end

  def create
    @resultado = Resultado.new(resultado_params)
    if @resultado.save
      flash[:notice] = "Creacion de resultado exitosa"
      redirect_to @resultado
    else
      flash[:alert] = "Error Creando resultado"
      render 'new'
    end
  end

  def show
    @resultado = Resultado.find(params[:id])

  end

  def edit
    @resultado = Resultado.find(params[:id])
  end

  def update
    if @resultado.update_attributes(post_params)
      flash[:notice] = "Actualizacion exitosa!"
      redirect_to resultado_path(@posts)
    else
      flash[:alert] = "Error no se pudo actualizar !"
      render :edit
    end
  end


  def delete
    if @resultado.delete
      flash[:notice] = "Borrado exitoso!"
      redirect_to resultados_path
    else
      flash[:alert] = "No se pudo borrar!"
    end
  end
  private
  def resultado_params
    params.require(:resultado).permit(:id,:nom_resultado, :enfrentamiento, :puntos_partido, :goles_marcados, :goles_recibidos )
  end
  def find_resultado
    @resultado = Resultado.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/grupo_helper.rb
module GrupoHelper
end

app/helpers/resultados_helper.rb
module ResultadosHelper
end

app/helpers/tipo_equipo_helper.rb
module TipoEquipoHelper
end

app/helpers/tipoequipo_helper.rb
module TipoequipoHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/equipos/_form.html.erb
<%= form_for(@equipo) do |form| %>
  <% if @equipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@equipo.errors.count, "error") %> prohibited this equipo from being saved:</h2>

      <ul>
      <% @equipo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<% end %>

app/views/equipos/edit.html.erb
<h1>Editing Equipo</h1>

<%= render 'form', equipo: @equipo %>

<%= link_to 'Show', @equipo %> |
<%= link_to 'Back', equipos_path %>

app/views/equipos/index.html.erb
<h1>Listado de Equipos</h1>

<%= link_to 'Crear nuevo Equipo', new_equipo_path %>
<%= link_to 'Atras ', welcome_index_path %>

<table>
  <tr>
    <th>Codigo</th>
    <th>Nombre de Equipo</th>
    <th>Activo</th>
    <th>Fecha Creacion</th>
  </tr>

  <% @equipo.each do |equipo| %>
    <tr>
      <td><%= equipo.cod_equipo %></td>
      <td><%= equipo.nom_equipo %></td>
      <td><%= equipo.activo_equipo %></td>
      <td><%= equipo.fecha_creacion %></td>
      <td><%= equipo.porcentaje %></td>
      <td><%= link_to 'Mostrar', equipo_path(equipo) %></td>
      <td><%= link_to 'Editar', edit_equipo_path(equipo) %></td>
    </tr>
  <% end %>
</table>

app/views/equipos/new.html.erb
<h1>Nuevo Equipo</h1>

<%= simple_form_for :equipo , url: equipos_path do |f| %>
  <% if @equipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@equipo.errors.count, "error") %><br> No se pudo guardar el equipo:</h2>
      <ul>
        <% @equipo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  <p>
    <%= f.label :Codigo %><br>
    <%= f.text_field :cod_equipo %>
  </p>

  <p>
    <%= f.label :Nombre %><br>
    <%= f.text_field :nom_equipo %>
  </p>

  <p>
    <%= f.label :Promedio %><br>
    <%= f.text_field :porcentaje %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Volver Atras', equipos_path %>
<%= render 'form', equipo: @equipo %>

app/views/equipos/show.html.erb
<h1>Equipo:</h1>

<p>
  <strong>Nombre:</strong>
  <%= @equipo.nom_equipo %>
</p>

<p>
  <title>Descripcion:</title>
  <%= @equipo.activo_equipo %>
</p>

<p>
  <strong>Probabilidades de Ganar:</strong>
  <%= @equipo.porcentaje %>
</p>


<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_equipo_path(@equipo) %> |
<%= link_to 'Delete', @equipo, method: :delete, data: {confirm: 'Estas seguro?'} %>
<%= link_to 'Back', equipos_path %>

app/views/grupo/_form.html.erb
<%= form_for(grupo_index_path) do |form| %>
  <% if @grupos.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grupos.errors.count, "error") %> No se permitio este grupo de ser creado</h2>

      <ul>
      <% @grupos.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grupo/edit.html.erb
<h1>Editing Equipo</h1>

<%= render 'form', tipo_equipo: @grupos %>

<%= link_to 'Show', @grupos %> |
<%= link_to 'Back', grupo_index_path %>

app/views/grupo/index.html.erb
<h1>Listado de Grupos y sus equipos</h1>

<%= link_to 'Crear nuevo grupo', new_grupo_path %>
<%= link_to 'Atras ', welcome_index_path %>

<table>
  <tr>
    <th>Codigo</th>
    <th>Nombre</th>
    <th>Activo</th>
    <th>Descripcion</th>
  </tr>

  <% @grupos.each do |grupo| %>
    <tr>
      <td><%= grupo.cod_tipo_equipo %></td>
      <td><%= grupo.nom_tipo_equipo %></td>
      <td><%= grupo.activo_tipo_equipo %></td>
      <td><%= grupo.descripcion %></td>
      <td><%= link_to 'Mostrar', grupo_path(grupo) %></td>
      <td><%= link_to 'Editar', edit_grupo_path(grupo) %></td>
    </tr>
  <% end %>
</table>

app/views/grupo/new.html.erb
<h1>Grupo:</h1>

<%= simple_form_for :grupo,url: new_grupo_path do |f| %>
  <% if @grupos.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grupos.errors.count, "error") %><br> No se pudo guardar el grupo:</h2>
      <ul>
        <% @grupos.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :Codigo %><br>
    <%= f.text_field :cod_tipo_equipo %>
  </p>

  <p>
    <%= f.label :Nombre %><br>
    <%= f.text_area :nom_tipo_equipo %>
  </p>

  <p>
    <%= f.label :Descripcion %><br>
    <%= f.text_area :descripcion %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to 'Volver Atras', grupo_index_path %>
<%= render 'form', grupo: @grupos %>

app/views/grupo/show.html.erb
<h1>Grupo</h1>

<p>
  <strong>Grupo:</strong>
  <%=@grupos.nom_tipo_equipo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%=@grupos.descripcion %>
</p>


<p id="notice"><%= notice %></p>




<%= link_to 'Edit', edit_grupo_path(@grupos) %>
<%= link_to 'Delete', @grupos, method: :delete, data: {confirm: 'Estas seguro?'} %>
<%= link_to 'Back', grupo_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectoNucleo2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resultados/_form.html.erb
<%= form_for(@resultado) do |form| %>
  <% if @resultado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resultado.errors.count, "error") %> prohibited this resultado from being saved:</h2>

      <ul>
      <% @resultado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resultados/edit.html.erb
<h1>Editing Resultados</h1>

<%= render 'form', resultados: @resultados %>

<%= link_to 'Show', @resultados %> |
<%= link_to 'Back', resultados_path %>

app/views/resultados/index.html.erb
<h1>Listado de Resultados</h1>

<%= link_to 'Crear nuevo Resultado', new_resultado_path %>
<%= link_to 'Atras ', welcome_index_path %>

<table>
  <tr>
    <th>Codigo</th>
    <th>Enfrentamiento</th>
    <th>Puntos de partido</th>
    <th>Goles marcados</th>
    <th>Goles recibidos</th>
  </tr>

  <% @resultado.each do |resultados| %>
    <tr>
      <td><%= resultados.cod_resultado %></td>
      <td><%= resultados.enfrentamiento %></td>
      <td><%= resultados.puntos_partido %></td>
      <td><%= resultados.goles_marcados %></td>
      <td><%= resultados.goles_recibidos %></td>
      <td><%= link_to 'Mostrar', resultado_path(@resultados) %></td>
    </tr>
  <% end %>
</table>

app/views/resultados/new.html.erb
<h1>Resultados</h1>

<%= simple_form_for :resultados, url:resultados_path do |f| %>
  <p>
    <%= f.label :cod_resultado %><br>
    <%= f.text_field :cod_resultado %>
  </p>

  <p>
    <%= f.label :enfrentamiento %><br>
    <%= f.text_area :enfrentamiento %>
  </p>

  <p>
    <%= f.label :puntos_partido %><br>
    <%= f.text_area :puntos_partido %>
  </p>

  <p>
    <%= f.label :goles_marcados %><br>
    <%= f.text_area :goles_marcados %>
  </p>

  <p>
    <%= f.label :goles_recibidos %><br>
    <%= f.text_area :goles_recibidos %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Volver Atras', resultados_path %>
<%= render 'form', resultado: @resultado %>

app/views/resultados/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_resultado_path(@resultados) %> |
<%= link_to 'Delete', @resultado, method: :delete, data: {confirm: 'Estas seguro?'} %>
<%= link_to 'Back', resultados_path %>

app/views/welcome/index.html.erb
<h1>Bienvenido a la Aplicación de control Estadistico de la FIFA 2018</h1>
<p></p>





<%=h link_to 'Equipos', controller: 'equipos' %>
<%=h link_to 'Grupos', controller: 'grupo' %>
<%=h link_to 'Resultados', controller: 'resultados' %>